env: "dev"

grpc:
  port: 1000
  timeout: 5s

client:
  auth_api:
    host: "auth-api"
    port: 1010
    timeout: 3s
    use_tls: true

  servers_api:
    host: "servers-api"
    port: 1011
    timeout: 3s
    use_tls: true