env: "dev"

grpc:
  port: 1000
  timeout: 5s

client:
  auth_api:
    host: "auth-api"
    port: 1010
    timeout: 3s
    use_tls: false

  servers_api:
    host: "servers-api"
    port: 1020
    timeout: 3s
    use_tls: false